### ISSUE TITLE
Python 3 or 2 ?

### ISSUE THREAD

**Issue by johannesmichael** [mstoffel-sag/c8yMQTT#3]
Hi

Trying to get it running, but ran in some problems.

piAgent.py is working, after outcommenting pressure (Init Failed)

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "piAgent.py", line 136, in sendMeasurements
    sendPressure()
  File "piAgent.py", line 50, in sendPressure
    tempString = "994,," + str(sense.get_pressure())
  File "/usr/lib/python3/dist-packages/sense_hat/sense_hat.py", line 621, in get_pressure
    self._init_pressure()  # Ensure pressure sensor is initialised
  File "/usr/lib/python3/dist-packages/sense_hat/sense_hat.py", line 559, in _init_pressure
    raise OSError('Pressure Init Failed')
OSError: Pressure Init Failed
`

sendMeasurements.py:
When running it in Python 3:
-  is missing brackets in print statements.
- Changed ConfigParser to configparser

How to use sendMeasurements.py?

Thanks for helping

Johannes

**Comment by mstoffel-sag** [comment]
Hi Johannes,

in general only Python3 is supported. Sorry, the complete sense-hat dir is just old examples which I will now remove. 

Better guidance you will get by checking the actual piAgent.py implementation.

Regards,

Marco
